### ISSUE TITLE
macOS dictionary settings not respected

### ISSUE THREAD

**Issue by harukizaemon** [irccloud/irccloud-desktop#97] opened 2017-08-14 23:15 UTC
I have my dictionary set to English U.K. with a fallback to English AU but as you can see from the screenshot, this isn't respected and irccloud wants me to change everything to American spelling:

<img width="548" alt="irccloud-dictionary" src="https://user-images.githubusercontent.com/333/29295781-a5067c42-8199-11e7-8436-e1658581d44a.png">

I had wondered if this was something to do with using a web view but Safari itself respects the dictionary settings:

<img width="671" alt="safari" src="https://user-images.githubusercontent.com/333/29295885-457ae38e-819a-11e7-9f4b-f8a3a0f1a2f0.png">

**Comment by jwheare** [comment] 2017-10-02 15:28
Hi, could you let me know if this still happens with the latest app release? https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0

**Comment by harukizaemon** [comment] 2017-10-02 21:39
Sadly, yes.

This is from notes app:

<img width="345" alt="notes app" src="https://user-images.githubusercontent.com/333/31100698-34eb8bde-a816-11e7-9be9-adcb70267aa5.png">

And this is from v 0.4.0:

<img width="524" alt="irccloud" src="https://user-images.githubusercontent.com/333/31100720-4dcc6a88-a816-11e7-93dd-5a3673b2f847.png">

**Comment by coffeejunk** [comment] 2017-12-11 10:29
this is still an issue in 0.5.1

<img width="234" alt="screenshot 2017-12-11 11 18 17" src="https://user-images.githubusercontent.com/205556/33826394-22b3f958-de65-11e7-9993-cdc9cb33d780.png">

<img width="173" alt="screenshot 2017-12-11 11 19 06" src="https://user-images.githubusercontent.com/205556/33826397-24707b5e-de65-11e7-933c-63fa68392031.png">

in addition to this the input starts to lag significantly after a couple of "misspelled" words have been added (I'm not sure if this is a related issue):

![out](https://user-images.githubusercontent.com/205556/33826789-66e652aa-de66-11e7-9496-b2ebd7764cec.gif)

**Comment by jwheare** [comment] 2017-12-11 10:39
This is a limitation of the spellcheck library we're using: https://github.com/electron-userland/electron-spellchecker/issues/61

**Comment by jwheare** [comment] 2017-12-11 10:45
Actually, that's not true, we're using https://github.com/mixmaxhq/electron-spell-check-provider not the previously linked library. It's possible that switching to that library may improve things but seems like there are still issues. We'll try.

**Comment by jwheare** [comment] 2017-12-11 13:03
Well, I can no longer reproduce the original reported issue in the latest release (0.5.1). For english uk/australia, "analyze" is marked incorrect and "analyse" is marked correct. @harukizaemon can you confirm?

The issue reported by @coffeejunk is separate and due to the fact that no current electron spell checking system (including electron-spellchecker) supports multiple languages in a single block of text. I'll open a separate issue for that, but close this one.

**Closed by jwheare** 2017-12-11 13:03 UTC
