### ISSUE TITLE
Can't re-launch snap after closing it

### ISSUE THREAD

**Issue by petevg** [irccloud/irccloud-desktop#147] opened 2019-09-16 13:43 UTC
I'm on a laptop running Disco (18.10), with the package manager provided Gnome Shell.

I can install the snap, launch irccloud, and sign in. When I close the snap (via file -> quit), I can't relaunch. The process simply exits, with no errors or traces left in the logs (that I can see).

Logging in/out of my session and rebooting don't fix the issue. If I remove and reinstall the snap, I can once again launch irccloud once. I'm unable to launch it again after I quit.

The laptop is a Thinkpad T480, with both a built in and discrete GPU. I'm running my desktop off of the built in Intel GPU, with bumblebee setup for the discrete GPU (nothing was running on the discrete GPU during this test, though). I'd be happy to post anything else relevant.

**Comment by jwheare** [comment] 2019-09-16 14:41
Hi, I can't reproduce this in an Ubuntu 19.04 Disco Dingo vm from https://www.osboxes.org/ubuntu/

After quitting either via the file menu or clicking the orange x in the top right I can relaunch every time.

Does this issue also affect you with the unofficial snap from https://snapcraft.io/irccloud-desktop or from the AppImage release from here? https://github.com/irccloud/irccloud-desktop/releases/tag/v0.13.0

**Comment by petevg** [comment] 2019-09-17 09:06
Hi @jwheare. Thanks for following up!

This issue does not affect me w/ the unofficial snap. I've installed, opened, closed, then re-opened both from a terminal. Here's what happened with both:

Unofficial snap:
https://paste.ubuntu.com/p/kBKfmf6Yjw/

Official snap:
https://paste.ubuntu.com/p/KYMYNXZ4Rh/

**Comment by jwheare** [comment] 2019-09-17 10:12
Thanks for the extra detail. Does the same thing happen if you open it from the GUI/desktop icon?

**Comment by petevg** [comment] 2019-09-17 11:43
@jwheare Yes. I initially ran into the problem when launching from the GUI, and started launching from the terminal to get more information. (Sadly, it basically fails silently in both cases.)

**Comment by petevg** [comment] 2020-01-22 07:54
I came up with a workaround that got me a working version of the IRC cloud snap. I'm not sure that I understand my workaround, however ...

I noticed that I was able to re-launch the snap if I first deleted $HOME/snap/irccloud/current/.config. This wasn't ideal, as I this deleted my signed in status, and undid my changes to the config (like turning on the system tray icon and setting a larger font size).

After some experimentation, I discovered that I could relaunch the snap, with my config saved, if I deleted the just the following files in the .config dir:

-rw-r--r-- 1 petevg petevg  688 Jan 22 09:46 user-dirs.dirs
-rw-r--r-- 1 petevg petevg   36 Jan 22 09:46 user-dirs.dirs.md5sum
-rw-rw-r-- 1 petevg petevg    5 Mar 24  2018 user-dirs.locale
-rw-r--r-- 1 petevg petevg   36 Jan 22 09:46 user-dirs.locale.md5sum

Those files don't get recreated on relaunch. I suspect that I've probably broken some form of functionality by getting rid of them. But all the basic chat stuff seems to work, so that's good.

(Changing the permissions of the files instead of deleting them didn't make a difference. I didn't experiment with editing their contents.)

**Comment by petevg** [comment] 2020-01-28 16:19
It looks like this may have to do with some of the directories in userdirs-dirs being symlinks on my system. I filed a bug against snapd, because I don't think that this is necessarily the IRC Cloud snaps' fault: https://bugs.launchpad.net/snapd/+bug/1861174

At least that explains why no one else was seeing this bug. I don't think that most people get irritated by the default Documents and Videos folders in their $HOME dirs, and replace them with symlinks elsewhere.

**Comment by kenvandine** [comment] 2020-01-30 21:21
I think this would need fixing in [snapcraft-desktop-helpers](https://github.com/ubuntu/snapcraft-desktop-helpers)

Can you please file a bug there?

**Comment by jwheare** [comment] 2020-02-24 11:12
Closing this as it's an issue with snapd https://github.com/ubuntu/snapcraft-desktop-helpers/issues/202

**Closed by jwheare** 2020-02-24 11:12 UTC
