### ISSUE TITLE
Could we get some finer control over zoom levels/change the zoom level unit to 10%?

### ISSUE THREAD

**Issue by StateOfException** [irccloud/irccloud-desktop#77] opened 2016-12-19 20:43 UTC
At present, the app has what looks like 20% jumps between page zoom levels- unlike Chrome, which a lot of people coming from will be used to.

Given how necessary lower zoom levels are on lower-res displays (legacy 768p displays, for example), the current zoom level increment is quite jarringly large- the user has a choice between what seems like 100% zoom (too large) and 80% zoom (a bit uncomfortably small).

Chrome currently handles zoom in 10% increments- the finer control (that is, the 90% setting) makes it a bit more usable on smaller/low-res displays without getting to the point where readability issues start cropping up with text rendering. Is there any chance that same functionality could be incorporated into the app?

**Comment by jwheare** [comment] 2016-12-19 20:50
Dupe of #67

**Closed by jwheare** 2016-12-19 20:50 UTC
