### ISSUE TITLE
Heartbeat from another client doesn't update the dock badge count

### ISSUE THREAD

**Issue by c99koder** [irccloud/irccloud-desktop#31] opened 2016-05-06 21:27 UTC
Marked a channel as read on mobile, dock icon badge still displays "1"

**Comment by jwheare** [comment] 2016-06-26 10:56
I can't reproduce this. What was the page title before and after? Were there other unread buffers/highlights?

**Comment by jwheare** [comment] 2016-06-30 17:08
This is an issue with the web app, so closing it here.

**Closed by jwheare** 2016-06-30 17:08 UTC
Labels: initial-release-blocker
